#!/bin/sh

yum install -y nfs-utils
mkdir -p /efs
mount -t nfs4 -o nfsvers=4.1 $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).fs-710dfbd8.efs.us-west-2.amazonaws.com:/ /efs
