#!/bin/sh -x

. /ecsboot.env

GELF=gelf-es-relay
TCPJSON=tcpjson-es-relay

docker build -t $GELF https://github.com/mayfield/gelf-elasticsearch.git
docker rm $GELF 2>/dev/null
docker run \
    --detach \
    --publish 12201:12201/udp \
    --log-driver json-file \
    --name $GELF \
    $GELF \
        --instance_id $IID \
        --instance_ip $LOCALIP \
        $ELASTICSEARCH_HOST/$ELASTICSEARCH_GELF_URN

docker build -t $TCPJSON https://github.com/mayfield/tcpjson-elasticsearch.git
docker rm $TCPJSON 2>/dev/null
docker run \
    --detach \
    --name $TCPJSON \
    --log-driver json-file \
    $TCPJSON $ELASTICSEARCH_HOST/$ELASTICSEARCH_TCPJSON_URN
