#!/bin/sh -x

docker rm logstash 2>/dev/null
docker run \
    --detach \
    --publish 12201:12201/udp \
    --publish 19831 \
    --name logstash \
    logstash -e '
        input {
            tcp {
                port => 19831
                codec => json
            }
            gelf {}
        }
        output {
            elasticsearch {
                hosts => ["'$ELASTICSEARCH_HOST'"]
            }
        }
        filter {
            mutate {
                gsub => [
                    "message",
                    "(\e\[[0-9;]*[mH]|\e\]0;|\r|\e\(B|\e\[[HJK]|\e\[\?1)",
                    ""
                ]
            }
            if [message] == "" {
                drop {}
            }
            if [command] == "apache2-foreground" {
                grok {
                    match => {
                        "message" => "%{COMBINEDAPACHELOG}"
                    }
                }
                geoip {
                    source => "clientip"
                }
            }
        }
    '
