#!/bin/sh -xe

ENV=/ecsboot.env

. $ENV

CONSUL_SERVERS=$(docker run --rm uzyexe/nmap -p 8300 -n -T4 --open -oG - \
    $SUBNETS | grep "Status: Up" | awk '{print $2}' | xargs)
echo "CONSUL_SERVERS=\"$CONSUL_SERVERS\"" >> $ENV
