#!/bin/sh -x

. /ecsboot.env

JOIN_ARGS=$(for x in $CONSUL_SERVERS; do echo -retry-join=$x ; done)

mkdir -p /hostroot/ecs/consul
docker run -d \
    --net host \
    -e 'CONSUL_ALLOW_PRIVILEGED_PORTS=' \
    -v /ecs/consul:/consul/data \
    consul \
        agent -server \
        -dns-port=53 \
        -advertise=$LOCALIP \
        -node=$IID \
        -bootstrap-expect=3 \
        -ui \
        $JOIN_ARGS \
        -retry-max=30 \
        -retry-interval=10s
