#!/bin/sh -x

docker run \
    --detach \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --link logstash:logstash \
    jmayfield/docker-stats -- \
        --statsinterval 60 \
        --host logstash:19831
