#!/bin/sh -x

docker run \
    --detach \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --link tcpjson-es-relay:relay \
    jmayfield/docker-stats -- \
        --statsinterval 300 \
        --host relay:19831
